(()=>{if(window.__councilBridge)return;window.__councilBridge=true;
const host=location.hostname;const provider=host==='chatgpt.com'?'ChatGPT':host==='grok.com'?'Grok':'Gemini';
const configs={ChatGPT:{composer:['#prompt-textarea[contenteditable="true"]','textarea#prompt-textarea','#prompt-textarea [contenteditable="true"]','textarea[data-id="root"]','[contenteditable="true"][data-lexical-editor="true"]','[contenteditable="true"][role="textbox"]','[contenteditable="true"].ProseMirror','form textarea','main textarea','[contenteditable="true"][data-placeholder]'],answers:['[data-message-author-role="assistant"]'],send:['button[data-testid="send-button"]','button[aria-label="Send prompt"]','button[data-testid="composer-send-button"]','button[aria-label="Send message"]'],stop:['button[data-testid="stop-button"]','button[aria-label="Stop streaming"]']},Grok:{composer:['textarea','[contenteditable="true"][role="textbox"]','[contenteditable="true"]'],answers:['[data-message-author-role="assistant"]','[data-testid="message-bubble"]','.message-bubble'],send:['button[aria-label="Send message"]','button[aria-label="Send"]','button[type="submit"]'],stop:['button[aria-label="Stop generating"]','button[aria-label="Stop"]']},Gemini:{composer:['rich-textarea [contenteditable="true"]','[contenteditable="true"][role="textbox"]'],answers:['model-response .markdown','model-response message-content','model-response'],send:['button.send-button','button[aria-label="Send message"]'],stop:['button[aria-label="Stop response"]','button[aria-label="Stop generating"]']}};
const c=configs[provider];let active=null;
const visible=e=>!!(e&&e.getClientRects().length);
function roots(){const out=[document];for(let i=0;i<out.length;i++)for(const el of out[i].querySelectorAll('*'))if(el.shadowRoot)out.push(el.shadowRoot);return out;}
const find=selectors=>{const scopes=roots();for(const selector of selectors){for(const root of scopes){const result=[...root.querySelectorAll(selector)].find(visible);if(result)return result;}}return undefined;};
function composer(){const candidate=find(c.composer);if(!candidate)return undefined;if(candidate.matches('textarea,[contenteditable="true"]'))return candidate;return [...candidate.querySelectorAll('textarea,[contenteditable="true"]')].find(visible);}
async function probe(){let editor=composer();for(let n=0;!editor&&n<12;n++){await sleep(500);editor=composer();}return {ready:!!editor,provider,error:'Chat input not detected. Refresh this provider tab, wait for it to load, then check connections again.'};}
function answers(){for(const s of c.answers){const nodes=[...document.querySelectorAll(s)].filter(visible);if(nodes.length)return nodes.map(e=>(e.innerText||'').trim()).filter(Boolean);}return [];}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function setText(el,text){el.focus();if(el instanceof HTMLTextAreaElement){Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,text);el.dispatchEvent(new Event('input',{bubbles:true}));}else{document.execCommand('selectAll',false);if(!document.execCommand('insertText',false,text)){el.textContent=text;el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));}}}
async function generate(msg){if(active)throw Error('This provider already has a Council request running.');if(find(c.stop))throw Error('The provider is already generating. Wait before retrying.');const editor=composer();if(!editor)throw Error('No chat composer found. Sign in and open a fresh chat.');if((editor.value||editor.innerText||'').trim())throw Error('The provider composer has unsent text. Clear it before sending.');const before=answers();const request={cancelled:false};active=request;try{setText(editor,msg.prompt);await sleep(600);const send=find(c.send);if(!send||send.disabled)throw Error('Send button not found or disabled. The prompt is in the provider tab; send it manually and paste the reply.');send.click();let last='',stable=0,sawGeneration=false;const start=Date.now();while(Date.now()-start<240000){await sleep(1200);if(request.cancelled)throw Error('Cancelled.');const list=answers();const current=list.at(-1)||'';if(current.includes(msg.prompt)||current.startsWith('You are '+provider+', a participant in an AI group conversation'))continue;const generating=!!find(c.stop);sawGeneration||=generating;const changed=list.length>before.length||(current&&current!==before.at(-1));if(changed&&current){stable=current===last?stable+1:0;last=current;if(!generating&&stable>=5&&(sawGeneration||Date.now()-start>15000))return {ok:true,text:current};}}throw Error('Reply collection timed out. Check the provider tab and paste its answer using Manual reply.');}finally{active=null;}}
chrome.runtime.onMessage.addListener((msg,_sender,reply)=>{if(msg.type==='probe'){probe().then(reply).catch(e=>reply({ready:false,error:e.message}));return true;}if(msg.type==='cancel'){if(active)active.cancelled=true;find(c.stop)?.click();reply({ok:true});return;}if(msg.type==='generate'){generate(msg).then(reply).catch(e=>reply({ok:false,error:e.message}));return true;}});
})();