(()=>{if(window.__councilBridge)return;window.__councilBridge=true;
const host=location.hostname;const provider=host==='chatgpt.com'?'ChatGPT':host==='grok.com'?'Grok':'Gemini';
const configs={ChatGPT:{composer:['#prompt-textarea[contenteditable="true"]','textarea#prompt-textarea','#prompt-textarea [contenteditable="true"]','textarea[data-id="root"]','[contenteditable="true"][data-lexical-editor="true"]','[contenteditable="true"][role="textbox"]','[contenteditable="true"].ProseMirror','form textarea','main textarea','[contenteditable="true"][data-placeholder]'],answers:['[data-message-author-role="assistant"]'],send:['button[data-testid="send-button"]','button[aria-label="Send prompt"]','button[data-testid="composer-send-button"]','button[data-testid="composer-submit-button"]','#composer-submit-button','button[aria-label="Send"]','button[aria-label="Send message"]'],stop:['button[data-testid="stop-button"]','button[aria-label="Stop streaming"]']},Grok:{composer:['textarea[placeholder*="Ask"]','textarea[placeholder*="ask"]','form textarea','[contenteditable="true"][role="textbox"]','[contenteditable="true"]','textarea'],answers:['[data-message-author-role="assistant"]','[data-testid="message-bubble"]','.message-bubble'],send:['button[aria-label="Send message"]','button[aria-label="Send"]','button[type="submit"]'],stop:['button[aria-label="Stop generating"]','button[aria-label="Stop"]']},Gemini:{composer:['rich-textarea [contenteditable="true"]','[contenteditable="true"][role="textbox"]'],answers:['model-response .markdown','model-response message-content','model-response'],send:['button.send-button','button[aria-label="Send message"]'],stop:['button[aria-label="Stop response"]','button[aria-label="Stop generating"]']}};
const c=configs[provider];let active=null;
const visible=e=>!!(e&&e.getClientRects().length);
function roots(){const out=[document];for(let i=0;i<out.length;i++)for(const el of out[i].querySelectorAll('*'))if(el.shadowRoot)out.push(el.shadowRoot);return out;}
const find=selectors=>{const scopes=roots();for(const selector of selectors){for(const root of scopes){const result=[...root.querySelectorAll(selector)].find(visible);if(result)return result;}}return undefined;};
function composer(){const candidate=find(c.composer);if(!candidate)return undefined;if(candidate.matches('textarea,[contenteditable="true"]'))return candidate;return [...candidate.querySelectorAll('textarea,[contenteditable="true"]')].find(visible);}
async function probe(){let editor=composer();for(let n=0;!editor&&n<12;n++){await sleep(500);editor=composer();}return {ready:!!editor,provider,error:'Chat input not detected. Refresh this provider tab, wait for it to load, then check connections again.'};}
function answers(){for(const s of c.answers){const nodes=[...document.querySelectorAll(s)].filter(visible);if(nodes.length)return nodes.map(e=>(e.innerText||'').trim()).filter(Boolean);}return [];}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function editorText(el){return (el instanceof HTMLTextAreaElement ? el.value : (el.innerText || el.textContent || '')).trim();}
function ownedDraft(text){return text.startsWith('You are '+provider+', a participant in an AI group conversation') && text.includes('SHARED TRANSCRIPT');}
function setText(el,text){el.focus();if(el instanceof HTMLTextAreaElement){Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,text);el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));el.dispatchEvent(new Event('change',{bubbles:true}));}else{const range=document.createRange();range.selectNodeContents(el);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);if(!document.execCommand('insertText',false,text)){el.textContent=text;el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));}}}
function sendButton(editor){const exact=find(c.send);if(exact&&!exact.disabled&&exact.getAttribute('aria-disabled')!=='true')return exact;const form=editor.closest('form');if(form){return [...form.querySelectorAll('button')].find(b=>visible(b)&&!b.disabled&&b.getAttribute('aria-disabled')!=='true'&&(b.type==='submit'||/^(send|send message|send prompt|submit)$/i.test((b.getAttribute('aria-label')||b.title||b.innerText||'').trim())));}return undefined;}
async function submit(editor,request){for(let n=0;n<20;n++){if(request.cancelled)throw Error('Cancelled.');const button=sendButton(editor);if(button){button.click();return;}await sleep(400);}editor.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true}));editor.dispatchEvent(new KeyboardEvent('keyup',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true}));}
async function generate(msg){if(active)throw Error('This provider already has a Council request running.');if(find(c.stop))throw Error('The provider is already generating. Wait before retrying.');const editor=composer();if(!editor)throw Error('No chat composer found. Sign in and open a fresh chat.');const draft=editorText(editor);if(draft&&!ownedDraft(draft))throw Error('This tab has a draft that Council did not write. Clear it in the provider tab or open an empty chat.');const before=answers();const request={cancelled:false};active=request;try{setText(editor,msg.prompt);await sleep(600);await submit(editor,request);let accepted=false;for(let n=0;n<12;n++){if(request.cancelled)throw Error('Cancelled.');if(!editorText(editor)||find(c.stop)||answers().some(t=>!before.includes(t)&&!t.includes(msg.prompt))){accepted=true;break;}await sleep(500);}if(!accepted){if(editorText(editor)===msg.prompt.trim())setText(editor,'');throw Error('The website did not accept the send action. Council cleared its leftover prompt. Open the provider tab and retry; if it persists, send a screenshot of its input and send button.');}let last='',stable=0,sawGeneration=false;const start=Date.now();while(Date.now()-start<240000){await sleep(1200);if(request.cancelled)throw Error('Cancelled.');const list=answers();const current=list.at(-1)||'';if(current.includes(msg.prompt)||current.startsWith('You are '+provider+', a participant in an AI group conversation'))continue;const generating=!!find(c.stop);sawGeneration||=generating;const changed=list.length>before.length||(current&&current!==before.at(-1));if(changed&&current){stable=current===last?stable+1:0;last=current;if(!generating&&stable>=5&&(sawGeneration||Date.now()-start>15000))return {ok:true,text:current};}}throw Error('Reply collection timed out. Check the provider tab and paste its answer using Manual reply.');}finally{active=null;}}
chrome.runtime.onMessage.addListener((msg,_sender,reply)=>{if(msg.type==='probe'){probe().then(reply).catch(e=>reply({ready:false,error:e.message}));return true;}if(msg.type==='cancel'){if(active)active.cancelled=true;find(c.stop)?.click();reply({ok:true});return;}if(msg.type==='generate'){generate(msg).then(reply).catch(e=>reply({ok:false,error:e.message}));return true;}});
})();