(()=>{if(window.__councilBridge)return;window.__councilBridge=true;
const host=location.hostname;const provider=host==='chatgpt.com'?'ChatGPT':host==='grok.com'?'Grok':'Gemini';
const configs={ChatGPT:{composer:['#prompt-textarea[contenteditable="true"]','textarea#prompt-textarea','#prompt-textarea [contenteditable="true"]','textarea[data-id="root"]','[contenteditable="true"][data-lexical-editor="true"]','[contenteditable="true"][role="textbox"]','[contenteditable="true"].ProseMirror','form textarea','main textarea','[contenteditable="true"][data-placeholder]'],answers:['[data-message-author-role="assistant"] .markdown','[data-message-author-role="assistant"]','[data-testid="assistant-message"]','[data-testid^="conversation-turn-"] .markdown','article .markdown','.agent-turn .markdown','.markdown.prose','[data-message-author-role="assistant"] [dir="auto"]','[data-testid="conversation-turn"] .markdown','[data-testid="conversation-turn"] [data-message-author-role="assistant"]','[data-role="assistant"]','[data-author="assistant"]','[class*="MarkdownRoot-"]','.markdown'],send:['button[data-testid="send-button"]','button[aria-label="Send prompt"]','button[data-testid="composer-send-button"]','button[data-testid="composer-submit-button"]','#composer-submit-button','button[aria-label="Send"]','button[aria-label="Send message"]'],stop:['button[data-testid="stop-button"]','button[aria-label="Stop streaming"]']},Grok:{composer:['textarea[placeholder*="Ask"]','textarea[placeholder*="ask"]','form textarea','[contenteditable="true"][role="textbox"]','[contenteditable="true"]','textarea'],answers:['[data-message-author-role="assistant"] .markdown','[data-testid="message-bubble"] .markdown','.message-bubble .markdown','.response-content-markdown','[data-message-author-role="assistant"]','[data-testid="message-bubble"]','.message-bubble'],send:['button[aria-label="Send message"]','button[aria-label="Send"]','button[type="submit"]'],stop:['button[aria-label="Stop generating"]','button[aria-label="Stop"]']},Gemini:{composer:['rich-textarea [contenteditable="true"]','[contenteditable="true"][role="textbox"]'],answers:['model-response .markdown','model-response message-content','model-response'],send:['button.send-button','button[aria-label="Send message"]'],stop:['button[aria-label="Stop response"]','button[aria-label="Stop generating"]']}};
const c=configs[provider];let active=null;const requests=new Map();
const visible=e=>!!(e&&e.getClientRects().length);
function roots(){const out=[document];for(let i=0;i<out.length;i++)for(const el of out[i].querySelectorAll('*'))if(el.shadowRoot)out.push(el.shadowRoot);return out;}
const find=selectors=>{const scopes=roots();for(const selector of selectors){for(const root of scopes){const result=[...root.querySelectorAll(selector)].find(visible);if(result)return result;}}return undefined;};
function composer(){const candidate=find(c.composer);if(!candidate)return undefined;if(candidate.matches('textarea,[contenteditable="true"]'))return candidate;return [...candidate.querySelectorAll('textarea,[contenteditable="true"]')].find(visible);}
async function probe(){let editor=composer();for(let n=0;!editor&&n<12;n++){await sleep(500);editor=composer();}return {ready:!!editor,provider,conversation:location.pathname,error:'Chat input not detected. Refresh this provider tab, wait for it to load, then check connections again.'};}
function cleanReply(text){return text.split('\n').filter(line=>!/^\s*(Worked for \d+(?:\.\d+)?s|Thinking(?:…|\.\.\.)?|Analyzing the AI council room status|Copy|Good response|Bad response|Read aloud)\s*$/i.test(line)).join('\n').trim();}
function answers(){const scopes=roots();for(const selector of c.answers){const texts=scopes.flatMap(root=>[...root.querySelectorAll(selector)]).filter(e=>visible(e)&&!e.closest('[data-message-author-role="user"]')).map(e=>cleanReply(e.innerText||e.textContent||'')).filter(t=>t&&!ownedDraft(t));if(texts.length)return texts;}return [];}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function editorText(el){return (el instanceof HTMLTextAreaElement ? el.value : (el.innerText || el.textContent || '')).trim();}
function ownedDraft(text){return text.startsWith('COUNCIL SETUP:')||text.startsWith('NEW MESSAGES\n')|| text.startsWith('You are '+provider+', a participant in an AI group conversation') && text.includes('SHARED TRANSCRIPT');}
function setText(el,text){el.focus();if(el instanceof HTMLTextAreaElement){Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,text);el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));el.dispatchEvent(new Event('change',{bubbles:true}));}else{const range=document.createRange();range.selectNodeContents(el);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);if(!document.execCommand('insertText',false,text)){el.textContent=text;el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));}}}
function sendButton(editor){const exact=find(c.send);if(exact&&!exact.disabled&&exact.getAttribute('aria-disabled')!=='true')return exact;const form=editor.closest('form');if(form){return [...form.querySelectorAll('button')].find(b=>visible(b)&&!b.disabled&&b.getAttribute('aria-disabled')!=='true'&&(b.type==='submit'||/^(send|send message|send prompt|submit)$/i.test((b.getAttribute('aria-label')||b.title||b.innerText||'').trim())));}return undefined;}
async function submit(editor,request){for(let n=0;n<20;n++){if(request.cancelled)throw Error('Cancelled.');const button=sendButton(editor);if(button){button.click();return;}await sleep(400);}editor.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true}));editor.dispatchEvent(new KeyboardEvent('keyup',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true}));}
async function generate(msg){if(active)throw Error('This provider already has a Council request running.');if(find(c.stop))throw Error('The provider is already generating. Wait before retrying.');const editor=composer();if(!editor)throw Error('No chat composer found. Sign in and open a fresh chat.');const draft=editorText(editor);if(draft&&!ownedDraft(draft))throw Error('This tab has a draft that Council did not write. Clear it in the provider tab or open an empty chat.');const before=answers();const request={cancelled:false};active=request;try{setText(editor,msg.prompt);await sleep(600);await submit(editor,request);let accepted=false;for(let n=0;n<60;n++){if(request.cancelled)throw Error('Cancelled.');if(!editorText(editor)||find(c.stop)||answers().some(t=>!before.includes(t)&&!t.includes(msg.prompt))){accepted=true;break;}await sleep(500);}if(!accepted){throw Error('Send confirmation was not detected. Check the provider tab and use Import latest reply if it answered.');}const record=requests.get(msg.requestId);if(record){record.sent=true;record.conversation=location.pathname;}let last='',stable=0,sawGeneration=false;const start=Date.now();while(Date.now()-start<240000){await sleep(1200);if(request.cancelled)throw Error('Cancelled.');const list=answers();const current=list.at(-1)||'';if(current.includes(msg.prompt)||current.startsWith('You are '+provider+', a participant in an AI group conversation'))continue;const generating=!!find(c.stop);sawGeneration||=generating;const changed=list.length>before.length||(current&&current!==before.at(-1));if(changed&&current){stable=current===last?stable+1:0;last=current;if(!generating&&stable>=5&&(sawGeneration||Date.now()-start>15000))return {ok:true,text:current,sent:true,conversation:location.pathname};}}throw Error('Reply collection timed out. Check the provider tab and paste its answer using Manual reply.');}finally{active=null;}}
chrome.runtime.onMessage.addListener((msg,_sender,reply)=>{if(msg.type==='start'){if(active){reply({ok:false,error:'This provider is still processing a request.'});return;}requests.set(msg.requestId,{pending:true,sent:false});generate(msg).then(result=>requests.set(msg.requestId,{...result,pending:false})).catch(error=>{const prev=requests.get(msg.requestId);requests.set(msg.requestId,{...prev,pending:false,ok:false,error:error.message});});for(const [id,value] of requests)if(id!==msg.requestId&&!value.pending)requests.delete(id);reply({ok:true});return;}if(msg.type==='poll'){reply(requests.get(msg.requestId)||{ok:false,error:'The provider page reloaded during collection. Use Import latest reply.'});return;}if(msg.type==='collect'){const text=answers().filter(t=>!ownedDraft(t)).at(-1);reply(text?{ok:true,text}:{ok:false,error:'No assistant reply detected. Use Manual reply or send a screenshot of the provider response.'});return;}if(msg.type==='probe'){probe().then(reply).catch(e=>reply({ready:false,error:e.message}));return true;}if(msg.type==='cancel'){if(active)active.cancelled=true;find(c.stop)?.click();reply({ok:true});return;}if(msg.type==='generate'){generate(msg).then(reply).catch(e=>reply({ok:false,error:e.message}));return true;}});
})();